name: ci-Test

on:
  push:
    branches: [ main, gh-actions ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go
      - name: Test
        run: make test
